spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rntn_db_dev?useSSL=false
    username: dev_user
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    clean-disabled: false

logging:
  level:
    com.example.rntn: DEBUG
    org.hibernate.SQL: DEBUG

